### ISSUE TITLE
git2r

### ISSUE THREAD

**Issue by maelle** [lorenzwalthert/gitsum#32]
Nice package! Just a question, is there any reason why you don't use the `git2r` package?

**Comment by lorenzwalthert** [comment]
Good question 😊. I was hesitating to open an issue in the `git2r` repo to discuss overlap. I only looked at the repo quickly and it seems to have a different focus. Do you have any experience with it? I checked out the [documentation of libgit2](https://libgit2.github.com/libgit2/ex/HEAD/log.html) where it says about `git log`.
> This does not have:
> * Robust error handling
> * Colorized or paginated output formatting
> * Most of the git log options

Which was enough for me to continue developing `gitsum`. I am aware that you could also use commands other than `git log`  to get a comprehensive history, but I did not see quickly how `git2r` could help me here and I enjoyed working on it so I continued anyways 😄

**Comment by jonmcalder** [comment]
It's good that you raised this @maelle - @lorenzwalthert and I were just chatting about this a month ago!

**Comment by maelle** [comment]
Thank you for the explanations! And wow 👏 great job on labelling issues!
