### ISSUE TITLE
Error in assert_gitsum_repo(path) : . is not a gitsum repo

### ISSUE THREAD

**Issue by sanjmeh** [lorenzwalthert/gitsum#43]
While `parse_log_simple()` works fine, when I run `parse_log_detailed()` on the same current directory which definitely has a git repository, it emits this error consistently:
```Error in assert_gitsum_repo(path) : . is not a gitsum repo```

I have tried in at least 2 different working directories and also tried giving the path in the argument instead of the default `path = "."`

What could be wrong?

**Comment by lorenzwalthert** [comment]
Thanks. It's unfortunate but you must initialize the gitsum repo (not to be confused with git) with `gitsum::init_gitsum()` as shown in the README before. I fixed this with 57db0f14. So now it should also work without initializing.

**Comment by lorenzwalthert** [comment]
Does it?

**Comment by sanjmeh** [comment]
Just tried. It worked after the init_gitsum. Thanks for the prompt response. i will be over next few days using your package. Will also read the documentation properly.

**Comment by lorenzwalthert** [comment]
Ok, cool. Note that the package is in life cycle *experimental* and not currently developed actively. I am happy to improve the package and documentation upon your suggestions. You are also welcomed to submit PRs. In particular the reporting tools are not well tested. But I think the building blocks `parse_log_simple()` and `parse_log_detailed()` should work as expected.
