### ISSUE TITLE
deprecation-warning using gitsum::init_gitsum() & error in gitsum::add_line_history() after parse_log_detailed()

### ISSUE THREAD

**Issue by cathblatter** [lorenzwalthert/gitsum#47]
Hi @lorenzwalthert 

thanks for this awesome package!! I use it quite regularly to track my work across different projects

I encounter two things: 

1) every time I use `gitsum::init_gitsum()` I get the warning below 
![Screenshot 2021-01-04 at 13 05 48](https://user-images.githubusercontent.com/24943957/103534727-bc37de80-4e8f-11eb-9c12-5eadb3e23d97.png)

2) when following the README Example steps, I fail to `add_line_history()` in this steps: 

```
library(tidyverse)

gitsum::init_gitsum()

log <- 
  gitsum::parse_log_detailed()
log

#error here
log %>% 
  gitsum::add_line_history()
```

![Screenshot 2021-01-04 at 13 12 10](https://user-images.githubusercontent.com/24943957/103534857-fdc88980-4e8f-11eb-87e3-9a5f1bda773c.png)

running `gitsum::report_git()` works fine, I think the `unnest()`-call was missing.

would it be ok to fork & start a PR with suggested corrections? thanks for your reply!

**Comment by lorenzwalthert** [comment]
Hi. It's currently not actively maintained tbh from my side. Sure, PRs are great to fix it. 😄
